/**
 * ============================================================================
 * StoreForge AI
 * AI Product Model
 * ============================================================================
 *
 * File:
 * backend/src/modules/products/productAI.model.js
 *
 * Purpose:
 * - Store AI-generated product information
 * - Keep product generation history/context
 * - Store SEO content generated by AI
 * - Store product marketing information
 * - Track AI generation status
 * - Associate generated products with a StoreForge store
 *
 * IMPORTANT:
 * This model is for the StoreForge store/product generator.
 * It is NOT the Shopify chatbot product model.
 *
 * ============================================================================
 */

'use strict';

const mongoose = require('mongoose');


// ============================================================================
// SUB-SCHEMAS
// ============================================================================

const imageSchema = new mongoose.Schema(
  {
    url: {
      type: String,
      trim: true,
      maxlength: 2000
    },

    altText: {
      type: String,
      trim: true,
      maxlength: 500
    },

    position: {
      type: Number,
      min: 0
    }
  },
  {
    _id: false
  }
);


const variantSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      trim: true,
      maxlength: 250
    },

    option1: {
      type: String,
      trim: true,
      maxlength: 100
    },

    option2: {
      type: String,
      trim: true,
      maxlength: 100
    },

    option3: {
      type: String,
      trim: true,
      maxlength: 100
    },

    price: {
      type: Number,
      min: 0
    },

    compareAtPrice: {
      type: Number,
      min: 0
    },

    sku: {
      type: String,
      trim: true,
      maxlength: 100
    },

    barcode: {
      type: String,
      trim: true,
      maxlength: 100
    },

    inventoryQuantity: {
      type: Number,
      min: 0,
      default: 0
    },

    taxable: {
      type: Boolean,
      default: true
    },

    requiresShipping: {
      type: Boolean,
      default: true
    }
  },
  {
    _id: false
  }
);


// ============================================================================
// SEO SUB-SCHEMA
// ============================================================================

const seoSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      trim: true,
      maxlength: 255
    },

    description: {
      type: String,
      trim: true,
      maxlength: 500
    },

    keywords: [
      {
        type: String,
        trim: true,
        maxlength: 100
      }
    ],

    handle: {
      type: String,
      trim: true,
      maxlength: 255
    }
  },
  {
    _id: false
  }
);


// ============================================================================
// MARKETING SUB-SCHEMA
// ============================================================================

const marketingSchema = new mongoose.Schema(
  {
    shortDescription: {
      type: String,
      trim: true,
      maxlength: 1000
    },

    sellingPoints: [
      {
        type: String,
        trim: true,
        maxlength: 500
      }
    ],

    benefits: [
      {
        type: String,
        trim: true,
        maxlength: 500
      }
    ],

    features: [
      {
        type: String,
        trim: true,
        maxlength: 500
      }
    ],

    useCases: [
      {
        type: String,
        trim: true,
        maxlength: 500
      }
    ],

    targetAudience: {
      type: String,
      trim: true,
      maxlength: 2000
    },

    callToAction: {
      type: String,
      trim: true,
      maxlength: 300
    }
  },
  {
    _id: false
  }
);


// ============================================================================
// AI GENERATION SUB-SCHEMA
// ============================================================================

const aiGenerationSchema = new mongoose.Schema(
  {
    model: {
      type: String,
      trim: true,
      maxlength: 100
    },

    provider: {
      type: String,
      trim: true,
      maxlength: 100
    },

    promptVersion: {
      type: String,
      trim: true,
      maxlength: 100
    },

    generationId: {
      type: String,
      trim: true,
      maxlength: 200
    },

    tokensUsed: {
      type: Number,
      min: 0
    },

    generationTimeMs: {
      type: Number,
      min: 0
    },

    generatedAt: {
      type: Date
    }
  },
  {
    _id: false
  }
);


// ============================================================================
// PRODUCT AI SCHEMA
// ============================================================================

const productAISchema = new mongoose.Schema(
  {

    // ------------------------------------------------------------------------
    // OWNER
    // ------------------------------------------------------------------------

    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true
    },


    // ------------------------------------------------------------------------
    // STORE
    // ------------------------------------------------------------------------

    storeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Store',
      required: true,
      index: true
    },


    // ------------------------------------------------------------------------
    // SHOPIFY PRODUCT
    // ------------------------------------------------------------------------
    //
    // Filled after the generated product is created in Shopify.
    //

    shopifyProductId: {
      type: String,
      trim: true,
      maxlength: 100,
      index: true
    },


    // ------------------------------------------------------------------------
    // BASIC PRODUCT INFORMATION
    // ------------------------------------------------------------------------

    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 255
    },

    productType: {
      type: String,
      trim: true,
      maxlength: 150
    },

    vendor: {
      type: String,
      trim: true,
      maxlength: 150
    },

    category: {
      type: String,
      trim: true,
      maxlength: 150
    },

    subcategory: {
      type: String,
      trim: true,
      maxlength: 150
    },

    tags: [
      {
        type: String,
        trim: true,
        maxlength: 100
      }
    ],


    // ------------------------------------------------------------------------
    // PRODUCT DESCRIPTION
    // ------------------------------------------------------------------------

    description: {
      type: String,
      trim: true,
      maxlength: 20000
    },


    // ------------------------------------------------------------------------
    // PRICING
    // ------------------------------------------------------------------------

    pricing: {

      price: {
        type: Number,
        min: 0
      },

      compareAtPrice: {
        type: Number,
        min: 0
      },

      costPerItem: {
        type: Number,
        min: 0
      },

      currency: {
        type: String,
        trim: true,
        uppercase: true,
        maxlength: 10,
        default: 'USD'
      },

      pricingStrategy: {
        type: String,
        trim: true,
        maxlength: 100
      }

    },


    // ------------------------------------------------------------------------
    // PRODUCT IMAGES
    // ------------------------------------------------------------------------

    images: {
      type: [imageSchema],
      default: []
    },


    // ------------------------------------------------------------------------
    // PRODUCT VARIANTS
    // ------------------------------------------------------------------------

    variants: {
      type: [variantSchema],
      default: []
    },


    // ------------------------------------------------------------------------
    // PRODUCT OPTIONS
    // ------------------------------------------------------------------------

    options: [
      {
        name: {
          type: String,
          trim: true,
          maxlength: 100
        },

        values: [
          {
            type: String,
            trim: true,
            maxlength: 100
          }
        ]
      }
    ],


    // ------------------------------------------------------------------------
    // AI MARKETING CONTENT
    // ------------------------------------------------------------------------

    marketing: {
      type: marketingSchema,
      default: {}
    },


    // ------------------------------------------------------------------------
    // SEO
    // ------------------------------------------------------------------------

    seo: {
      type: seoSchema,
      default: {}
    },


    // ------------------------------------------------------------------------
    // PRODUCT SPECIFICATIONS
    // ------------------------------------------------------------------------

    specifications: {
      type: mongoose.Schema.Types.Mixed,
      default: {}
    },


    // ------------------------------------------------------------------------
    // PRODUCT DETAILS
    // ------------------------------------------------------------------------

    materials: [
      {
        type: String,
        trim: true,
        maxlength: 200
      }
    ],

    colors: [
      {
        type: String,
        trim: true,
        maxlength: 100
      }
    ],

    sizes: [
      {
        type: String,
        trim: true,
        maxlength: 100
      }
    ],


    // ------------------------------------------------------------------------
    // PRODUCT GENERATION INPUT
    // ------------------------------------------------------------------------

    generationInput: {

      productIdea: {
        type: String,
        trim: true,
        maxlength: 5000
      },

      targetMarket: {
        type: String,
        trim: true,
        maxlength: 1000
      },

      niche: {
        type: String,
        trim: true,
        maxlength: 500
      },

      tone: {
        type: String,
        trim: true,
        maxlength: 200
      },

      language: {
        type: String,
        trim: true,
        maxlength: 50,
        default: 'en'
      }

    },


    // ------------------------------------------------------------------------
    // AI GENERATION METADATA
    // ------------------------------------------------------------------------

    aiGeneration: {
      type: aiGenerationSchema,
      default: {}
    },


    // ------------------------------------------------------------------------
    // GENERATION STATUS
    // ------------------------------------------------------------------------

    status: {
      type: String,

      enum: [
        'draft',
        'generating',
        'generated',
        'review',
        'ready',
        'published',
        'failed',
        'archived'
      ],

      default: 'draft',

      index: true
    },


    // ------------------------------------------------------------------------
    // SHOPIFY SYNC STATUS
    // ------------------------------------------------------------------------

    shopifySync: {

      status: {
        type: String,

        enum: [
          'not_synced',
          'pending',
          'syncing',
          'synced',
          'failed'
        ],

        default: 'not_synced'
      },

      lastSyncedAt: {
        type: Date
      },

      lastError: {
        type: String,
        trim: true,
        maxlength: 2000
      }

    },


    // ------------------------------------------------------------------------
    // PUBLISH STATUS
    // ------------------------------------------------------------------------

    publishedAt: {
      type: Date
    },


    // ------------------------------------------------------------------------
    // ARCHIVE STATUS
    // ------------------------------------------------------------------------

    archivedAt: {
      type: Date
    }

  },
  {
    timestamps: true,

    versionKey: false
  }
);


// ============================================================================
// INDEXES
// ============================================================================

productAISchema.index({
  userId: 1,
  storeId: 1,
  createdAt: -1
});


productAISchema.index({
  storeId: 1,
  status: 1
});


productAISchema.index({
  storeId: 1,
  shopifyProductId: 1
});


productAISchema.index({
  title: 'text',
  description: 'text',
  tags: 'text'
});


// ============================================================================
// MODEL
// ============================================================================

const ProductAI = mongoose.model(
  'ProductAI',
  productAISchema
);


// ============================================================================
// EXPORT
// ============================================================================

module.exports = ProductAI;
